Excel Automation using Python.
neelshah2409/Bot-Collection pull request #158
Opened 2023-05-28 07:47 UTC by RoopakMallik

This solves issue #155  
Excel Automation using Python and Openpyxl Library.

2023-05-28 12:43 UTC, JigarJoshi04 requested changes
The PR should follow a Single responsibility principle (A PR should complete only one task at a time). There should be 2 PRs one for the excel automation and the other for the web scrapper bot as they bot are independent changes.

The code written by the author of this PR, seems to have lot of harcoded values and the code written is highly dependent on the hardcoded test data. The bot should be more genric, and the test case (test data) should be independent of the actual implementation of logic.

The issue attached doesn't contain the scope or requirement in detail, please add the requirements in more elaborate way. 

Requesting maintainers to do the changes before merging the PR.
Thanks

2023-05-28 12:43 UTC, JigarJoshi04 commented on Web Scrapper Bot/Readme.md
> +# Language, Libraries and Modules used-
Please add a requirements.txt file.
You can use `pip freeze > requirements.txt` to generate requirement file.
And we can remove this from readme after that

2023-05-28 12:43 UTC, JigarJoshi04 commented on Excel_Automation_Python/main.py
> +    }
Why are we hardcoding data for a bot?

2023-05-28 12:44 UTC, JigarJoshi04 commented
If author has any issues or need help, please feel free to ping me on Discord, Linkedin or reply to this PR.
Thanks

2023-05-28 13:06 UTC, RoopakMallik commented
I have made the required changes in the web scrapping bot and have added a
requirement.txt file as instructed.
Please check if any further changes are required.

On Sun, 28 May 2023, 6:14 pm Jigar Joshi, ***@***.***> wrote:

> If author has any issues or need help, please feel free to ping me on
> Discord, Linkedin or reply to this PR.
> Thanks
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/neelshah2409/Bot-Collection/pull/158#issuecomment-1566126635>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQYMEQC36OXMKT4ZSE2RX33XINCCPANCNFSM6AAAAAAYRVU3FM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-05-28 13:24 UTC, JigarJoshi04 commented
Please check my comment https://github.com/neelshah2409/Bot-Collection/pull/158#pullrequestreview-1448237663
This PR needs those changes before getting merged.

2023-05-28 13:45 UTC, RoopakMallik commented
I will fix the issues regarding the Excel Automation. Meanwhile please let
me know if the web scrapping bot needs any more changes.

On Sun, 28 May 2023, 6:55 pm Jigar Joshi, ***@***.***> wrote:

> Please check my comment #158 (review)
> <https://github.com/neelshah2409/Bot-Collection/pull/158#pullrequestreview-1448237663>
> This PR needs those changes before getting merged.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/neelshah2409/Bot-Collection/pull/158#issuecomment-1566139985>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQYMEQFXWLZARYEZDTTTPLLXING3FANCNFSM6AAAAAAYRVU3FM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-05-29 03:59 UTC, merged

2023-05-29 15:01 UTC, samanth2012 commented
#155 sir i was the first to rise this issue